# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20170706202513) do

  create_table "cities", force: :cascade do |t|
    t.string "name"
    t.string "url"
    t.string "country"
    t.float "business_freedom"
    t.float "business_freedom_teleport_score"
    t.float "freedom_from_corruption"
    t.float "freedom_from_corruption_teleport_score"
    t.float "lack_of_labor_restrictions"
    t.float "lack_of_labor_restrictions_teleport_score"
    t.float "time_to_open_a_business"
    t.float "time_to_open_a_business_teleport_score"
    t.float "urban_area_population_millions"
    t.float "population_density_in_people_sq_km_in_ua_center"
    t.float "population_density_in_people_sq_km_over_full_ua_as_defined_by_bounding_box"
    t.float "average_day_length_hours"
    t.float "average_number_of_clear_days_per_year"
    t.float "average_number_of_rainy_days_per_year"
    t.float "weather_av_possibility_sunshine"
    t.string "weather_average_high"
    t.string "weather_average_low"
    t.string "average_daily_solar_radiation_mj_m"
    t.string "weather_type"
    t.float "inflation_teleport_score"
    t.float "cost_apples"
    t.float "cost_bread"
    t.float "cost_cappuccino"
    t.float "cost_cinema"
    t.float "cost_fitness_club"
    t.float "cost_import_beer"
    t.float "cost_public_transport"
    t.float "cost_restaurant_meal"
    t.float "cost_taxi"
    t.float "restaurant_price_index"
    t.float "art_galleries_teleport_score"
    t.integer "culture_art_galleries_venue_count"
    t.float "cinemas_teleport_score"
    t.integer "culture_cinemas_venue_count"
    t.float "comedy_clubs_teleport_score"
    t.integer "culture_comedy_clubs_venue_count"
    t.float "concerts_teleport_score"
    t.integer "culture_concerts_venue_count"
    t.float "historical_sites_teleport_score"
    t.integer "culture_historical_sites_venue_count"
    t.float "museums_teleport_score"
    t.integer "culture_museums_venue_count"
    t.float "performing_arts_teleport_score"
    t.integer "culture_performing_arts_venue_count"
    t.float "sports_teleport_score"
    t.integer "culture_sports_venue_count"
    t.float "zoos_teleport_score"
    t.integer "culture_zoos_venue_count"
    t.string "currency_urban_area"
    t.float "currency_exchange_rate_per_us_dollar_for_urban_area"
    t.float "gdp_growth_rate"
    t.float "gdp_growth_rate_teleport_score"
    t.float "gdp_per_capita"
    t.float "gdp_per_capita_teleport_score"
    t.float "pisa_detail_happiness"
    t.float "pisa_detail_math_high_performers"
    t.float "pisa_detail_math_low_performers"
    t.float "country_mean_scores_in_pisa_math_test"
    t.float "pisa_detail_reading_high_performers"
    t.float "pisa_detail_reading_low_performers"
    t.float "country_mean_scores_in_pisa_reading_test"
    t.float "pisa_detail_science_high_performers"
    t.float "pisa_detail_science_low_performers"
    t.float "country_mean_scores_in_pisa_science_test"
    t.integer "pisa_maths_ranking"
    t.float "pisa_ranking"
    t.float "pisa_ranking_high_school_teleport_score"
    t.integer "pisa_reading_ranking"
    t.integer "pisa_science_ranking"
    t.float "university_quality_teleport_score"
    t.string "universities_best_ranked_name"
    t.integer "universities_best_ranked_rank"
    t.float "healthcare_expenditure_teleport_score"
    t.float "life_expectancy_years"
    t.float "life_expectancy_teleport_score"
    t.float "healthcare_quality_teleport_score"
    t.float "apartment_rent_large"
    t.float "apartment_rent_medium"
    t.float "apartment_rent_small"
    t.float "rent_index_teleport_score"
    t.float "elderly_people"
    t.float "life_expectancy_at_birth_in_country"
    t.float "median_age_in_country"
    t.float "unemployment_rate"
    t.float "employer_social_taxes_cap_soc_sec"
    t.float "employer_social_taxes_other"
    t.float "employer_social_taxes_soc_sec"
    t.float "startup_jobs_available"
    t.float "startup_job_availability_teleport_score"
    t.float "startup_salary_teleport_score"
    t.float "startup_salaries_detail"
    t.float "english_skills_detail"
    t.float "english_skills_teleport_score"
    t.string "spoken_languages"
    t.string "lgbt_detail_adoption"
    t.string "lgbt_detail_age_of_consent"
    t.string "lgbt_detail_changing_gender"
    t.string "lgbt_detail_conversion_therapy"
    t.string "lgbt_detail_discrimination"
    t.string "lgbt_detail_donating_blood"
    t.string "lgbt_detail_employment_discrimination"
    t.string "lgbt_detail_homosexuality"
    t.string "lgbt_detail_housing_discrimination"
    t.string "lgbt_detail_marriage"
    t.float "lgbt_equality_index"
    t.float "lgbt_equality_index_teleport_score"
    t.float "tolerance_towards_minorities_teleport_score"
    t.float "download_speed_mbps"
    t.float "internet_access_download_teleport_score"
    t.float "upload_speed_mbps"
    t.float "internet_access_upload_teleport_score"
    t.float "urban_area_elevation_meters"
    t.float "presence_of_hills_in_city"
    t.float "presence_of_mountains_in_city"
    t.float "median_peak_in_meters"
    t.float "elevation_hills_or_mountains_teleport_score"
    t.float "water_access_teleport_score"
    t.float "air_quality_teleport_score"
    t.float "cleanliness_teleport_score"
    t.float "drinking_water_quality_teleport_score"
    t.float "urban_greenery_teleport_score"
    t.float "crime_rate_teleport_score"
    t.float "gun_death_rate"
    t.float "lack_of_gun_related_deaths_teleport_score"
    t.float "gun_ownership"
    t.float "lack_of_guns_teleport_score"
    t.float "lack_of_guns_and_gun_related_deaths_teleport_score"
    t.float "coworking_spaces_teleport_score"
    t.float "events_count"
    t.integer "events_last_12_months"
    t.float "startup_events_teleport_score"
    t.integer "funderbeam_total_startups"
    t.integer "meetups_detail_total_events"
    t.integer "meetups_groups"
    t.integer "meetups_members"
    t.float "meetups_teleport_score"
    t.integer "startup_climate_investors"
    t.float "startup_climate_new_startups"
    t.float "average_monthly_increase_in_number_of_startups_teleport_score"
    t.float "startup_climate_scene_teleport_score"
    t.float "startups_teleport_score"
    t.integer "workfrom_coworking_spaces_count"
    t.float "company_profit_tax_rate"
    t.float "effective_company_profit_tax_rate_on_payouts_as_dividends_teleport_score"
    t.float "income_tax_level_teleport_score"
    t.float "tax_vat"
    t.float "time_overhead_company_taxes"
    t.float "traffic_handling_teleport_score"
    t.integer "airport_hub_index_detail"
    t.float "airport_hub_teleport_score"
    t.float "intercity_train_connectivity_teleport_score"
    t.float "venture_capital_teleport_score"
    t.string "funding_accelerator_names"
    t.float "funding_accelerators"
    t.float "funding_accelerators_detail"
    t.float "seaside_access"
    t.float "lgbt_detail_opinion_percent_in_favor"
    t.float "seaside_waterbody"
    t.float "weather_av_percent_chance_clear_skies"
    t.integer "employer_social_taxes_cap_other"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "favourite_cities", force: :cascade do |t|
    t.string "name"
    t.integer "user_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "users", force: :cascade do |t|
    t.string "email"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end
